import type { Creative, Client, AdAccount, Insight } from "./types"

export const clients: Client[] = [
  { 
    id: "1", 
    name: "Animale", 
    status: "active",
    spend: 45230,
    impressions: 1250000,
    clicks: 28500,
    ctr: 2.28,
    cpc: 1.59,
    cpm: 36.18,
    purchases: 892,
    cpa: 50.70,
    roas: 4.85,
    creativesCount: 24,
    activeCreatives: 18,
    topPerformer: "Summer Collection Hero"
  },
  { 
    id: "2", 
    name: "Farm Rio", 
    status: "active",
    spend: 62150,
    impressions: 1850000,
    clicks: 42300,
    ctr: 2.29,
    cpc: 1.47,
    cpm: 33.59,
    purchases: 1245,
    cpa: 49.92,
    roas: 5.12,
    creativesCount: 36,
    activeCreatives: 28,
    topPerformer: "Tropical Vibes Campaign"
  },
  { 
    id: "3", 
    name: "Cris Barros", 
    status: "active",
    spend: 28400,
    impressions: 720000,
    clicks: 15800,
    ctr: 2.19,
    cpc: 1.80,
    cpm: 39.44,
    purchases: 456,
    cpa: 62.28,
    roas: 3.82,
    creativesCount: 15,
    activeCreatives: 12,
    topPerformer: "Elegance Editorial"
  },
  { 
    id: "4", 
    name: "Osklen", 
    status: "active",
    spend: 35800,
    impressions: 980000,
    clicks: 21500,
    ctr: 2.19,
    cpc: 1.67,
    cpm: 36.53,
    purchases: 678,
    cpa: 52.80,
    roas: 4.21,
    creativesCount: 22,
    activeCreatives: 16,
    topPerformer: "Urban Street Style"
  },
]

export const adAccounts: AdAccount[] = [
  { id: "1", name: "Animale - Principal", clientId: "1" },
  { id: "2", name: "Animale - Outlet", clientId: "1" },
  { id: "3", name: "Farm Rio - Brasil", clientId: "2" },
  { id: "4", name: "Farm Rio - Global", clientId: "2" },
  { id: "5", name: "Cris Barros - Principal", clientId: "3" },
  { id: "6", name: "Osklen - Principal", clientId: "4" },
]

const fashionImages = [
  "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1485968579169-a6e9dc7c0ae0?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400&h=500&fit=crop",
  "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=500&fit=crop",
]

const creativeNames = [
  "Summer Collection Hero",
  "New Arrivals Carousel",
  "Sale Campaign Banner",
  "Lifestyle Video Lookbook",
  "Product Showcase Grid",
  "Brand Story Video",
  "Collection Launch",
  "Editorial Style",
  "Weekend Vibes",
  "Urban Collection",
  "Resort Wear",
  "Evening Collection",
]

const campaigns = [
  "Summer 2025 - Awareness",
  "Summer 2025 - Conversions",
  "Always On - Retargeting",
  "New Collection Launch",
  "Sale Season - Traffic",
]

export const creatives: Creative[] = Array.from({ length: 12 }, (_, i) => ({
  id: `creative-${i + 1}`,
  name: creativeNames[i % creativeNames.length],
  thumbnail: fashionImages[i % fashionImages.length],
  type: i % 3 === 0 ? "video" : "image",
  status: i % 4 === 0 ? "paused" : i % 5 === 0 ? "mixed" : "active",
  spend: Math.round(Math.random() * 15000 + 500),
  impressions: Math.round(Math.random() * 500000 + 10000),
  clicks: Math.round(Math.random() * 5000 + 100),
  ctr: Math.round((Math.random() * 3 + 0.5) * 100) / 100,
  cpc: Math.round((Math.random() * 2 + 0.3) * 100) / 100,
  cpm: Math.round((Math.random() * 20 + 5) * 100) / 100,
  purchases: Math.round(Math.random() * 200 + 10),
  cpa: Math.round((Math.random() * 80 + 20) * 100) / 100,
  roas: Math.round((Math.random() * 5 + 1) * 100) / 100,
  firstSeen: "2025-01-15",
  lastSeen: "2025-03-27",
  campaigns: campaigns.slice(0, Math.floor(Math.random() * 3) + 1),
  ads: [`Ad ${i + 1}A`, `Ad ${i + 1}B`],
}))

export const insights: Insight[] = [
  {
    id: "insight-1",
    type: "success",
    category: "performance",
    title: "Top performer da semana",
    description: "Este criativo superou a média de ROAS em 156% comparado aos demais da conta.",
    clientName: "Farm Rio",
    creativeName: "Tropical Vibes Campaign",
    creativeThumbnail: fashionImages[2],
    creativeType: "image",
    metric: "ROAS",
    value: 7.82,
    comparison: 156,
    date: "2025-03-27"
  },
  {
    id: "insight-2",
    type: "warning",
    category: "budget",
    title: "Orçamento próximo do limite",
    description: "A conta atingiu 92% do orçamento mensal com 4 dias restantes no mês.",
    clientName: "Animale",
    metric: "Budget",
    value: 92,
    date: "2025-03-27"
  },
  {
    id: "insight-3",
    type: "success",
    category: "creative",
    title: "Vídeo com alto engajamento",
    description: "Este vídeo tem CTR 2.3x maior que a média de vídeos da conta.",
    clientName: "Osklen",
    creativeName: "Urban Street Style",
    creativeThumbnail: fashionImages[6],
    creativeType: "video",
    metric: "CTR",
    value: 4.85,
    comparison: 230,
    date: "2025-03-26"
  },
  {
    id: "insight-4",
    type: "warning",
    category: "performance",
    title: "Queda de performance",
    description: "O CPA aumentou 45% nos últimos 7 dias comparado ao período anterior.",
    clientName: "Cris Barros",
    creativeName: "Elegance Editorial",
    creativeThumbnail: fashionImages[4],
    creativeType: "image",
    metric: "CPA",
    value: 78.50,
    comparison: -45,
    date: "2025-03-26"
  },
  {
    id: "insight-5",
    type: "info",
    category: "audience",
    title: "Nova audiência identificada",
    description: "Mulheres 35-44 apresentaram ROAS 82% superior à média geral.",
    clientName: "Farm Rio",
    metric: "ROAS",
    value: 5.92,
    comparison: 82,
    date: "2025-03-25"
  },
  {
    id: "insight-6",
    type: "success",
    category: "creative",
    title: "Imagem carousel performando bem",
    description: "Carousel com 5 imagens tem custo por compra 38% menor que imagens únicas.",
    clientName: "Animale",
    creativeName: "Summer Collection Hero",
    creativeThumbnail: fashionImages[0],
    creativeType: "image",
    metric: "CPA",
    value: 42.30,
    comparison: 38,
    date: "2025-03-25"
  },
  {
    id: "insight-7",
    type: "warning",
    category: "creative",
    title: "Criativo com baixa performance",
    description: "Este criativo está com ROAS 65% abaixo da média. Considere pausar.",
    clientName: "Cris Barros",
    creativeName: "Weekend Collection",
    creativeThumbnail: fashionImages[8],
    creativeType: "video",
    metric: "ROAS",
    value: 1.34,
    comparison: -65,
    date: "2025-03-24"
  },
  {
    id: "insight-8",
    type: "success",
    category: "performance",
    title: "Melhor semana do mês",
    description: "Total de compras 28% acima da média semanal do último mês.",
    clientName: "Osklen",
    metric: "Purchases",
    value: 186,
    comparison: 28,
    date: "2025-03-24"
  },
]

// Best performing creatives across all clients
export const topCreatives = [
  {
    id: "top-1",
    name: "Tropical Vibes Campaign",
    clientName: "Farm Rio",
    thumbnail: fashionImages[2],
    type: "image" as const,
    roas: 7.82,
    spend: 8450,
    purchases: 245,
    improvement: 156
  },
  {
    id: "top-2",
    name: "Summer Collection Hero",
    clientName: "Animale",
    thumbnail: fashionImages[0],
    type: "image" as const,
    roas: 6.45,
    spend: 12300,
    purchases: 312,
    improvement: 124
  },
  {
    id: "top-3",
    name: "Urban Street Style",
    clientName: "Osklen",
    thumbnail: fashionImages[6],
    type: "video" as const,
    roas: 5.92,
    spend: 6780,
    purchases: 156,
    improvement: 98
  },
  {
    id: "top-4",
    name: "Resort Collection",
    clientName: "Farm Rio",
    thumbnail: fashionImages[3],
    type: "video" as const,
    roas: 5.45,
    spend: 9200,
    purchases: 198,
    improvement: 86
  },
  {
    id: "top-5",
    name: "Evening Elegance",
    clientName: "Cris Barros",
    thumbnail: fashionImages[4],
    type: "image" as const,
    roas: 4.98,
    spend: 5400,
    purchases: 108,
    improvement: 72
  },
  {
    id: "top-6",
    name: "Street Fashion Video",
    clientName: "Osklen",
    thumbnail: fashionImages[9],
    type: "video" as const,
    roas: 4.76,
    spend: 7800,
    purchases: 142,
    improvement: 65
  },
]
